apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: damodarkumar/github-actions-terraform 
  name: aws-s3-bucket
spec:
  type: service
  lifecycle: production
  owner: platform-engineering-team
  provides:
    - type: GitHubAction
      targets:
        - damodarkumar/github-actions-terraform  # Replace with your GitHub repository in the format "owner/repo"
      implementsApis:
        - apiVersion: backstage.io/v1alpha1
          kind: GitHubAction
          name: invoke-terraform
          schema:
            url: https://github.com/damodarkumar/s3-bucket-aws/blob/main/.github/workflows/invoke.yml  # Replace with the actual URL of your workflow file
            method: post

